version: '3.8'

services:
  bookmarks:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      ADDRESS: 0.0.0.0
      PORT: 3000
      MONGO_URI: mongodb://bookmarksUser:mysecret@mongo:27017/bookmarks
    networks:
      - bookmarks_network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./containers/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bookmarks
    networks:
      - bookmarks_network

networks:
  bookmarks_network: null
